displayName=Mortimer Slayer Tracker
author=ruffensteint
description=Tracks Mortimer Slayer assignments and Road to 99 progress
tags=slayer,mortimer,tracker,discord
version=
plugins=com.ruffensteint.mortimerslayertracker.MortimerSlayerTrackerPlugin
build=standard
