package com.ruffensteint.mortimerslayertracker.service;

import java.util.Set;
import net.runelite.api.gameval.NpcID;

public final class SuperiorNpc
{
	private static final Set<Integer> IDS = Set.of(
		NpcID.SUPERIOR_CRAWLING_HAND,
		NpcID.SUPERIOR_CAVE_CRAWLER,
		NpcID.SUPERIOR_CAVE_CRAWLER_ICE,
		NpcID.SUPERIOR_BANSHEE,
		NpcID.SUPERIOR_KOUREND_BANSHEE,
		NpcID.SUPERIOR_ROCKSLUG,
		NpcID.SUPERIOR_COCKATRICE,
		NpcID.SUPERIOR_PYREFIEND,
		NpcID.SUPERIOR_PYRELORD,
		NpcID.SUPERIOR_BASILISK,
		NpcID.SUPERIOR_BASILISK_KNIGHT,
		NpcID.SUPERIOR_INFERNAL_MAGE,
		NpcID.SUPERIOR_BLOODVELD,
		NpcID.SUPERIOR_KOUREND_BLOODVELD,
		NpcID.SUPERIOR_JELLY,
		NpcID.SUPERIOR_KOUREND_JELLY,
		NpcID.SUPERIOR_CHILLED_JELLY,
		NpcID.SUPERIOR_CAVE_HORROR,
		NpcID.SUPERIOR_ABBERANT_SPECTRE,
		NpcID.SUPERIOR_KOUREND_SPECTRE,
		NpcID.SUPERIOR_DUSTDEVIL,
		NpcID.SUPERIOR_KURASK,
		NpcID.SUPERIOR_SMOKE_DEVIL,
		NpcID.SUPERIOR_GARGOYLE,
		NpcID.SUPERIOR_GARGOYLE_DEAD,
		NpcID.SUPERIOR_DARK_BEAST,
		NpcID.SUPERIOR_ABYSSAL_DEMON,
		NpcID.SUPERIOR_NECHRYAEL,
		NpcID.SUPERIOR_TUROTH,
		NpcID.SUPERIOR_WYRM_DARK,
		NpcID.SUPERIOR_WYRM_LIGHT,
		NpcID.SUPERIOR_DRAKE,
		NpcID.SUPERIOR_DRAKE_DEATH,
		NpcID.SUPERIOR_HYDRA,
		NpcID.SUPERIOR_WARPED_TERRORBIRD,
		NpcID.SUPERIOR_WARPED_TORTOISE,
		NpcID.SUPERIOR_ARAXYTE,
		NpcID.SUPERIOR_CUSTODIAN,
		NpcID.SUPERIOR_GRYPHON,
		NpcID.SUPERIOR_AQUANITE,
		NpcID.SUPERIOR_AQUANITE_NOLURE,
		NpcID.SUPERIOR_LAVA_STRYKEWYRM,
		NpcID.SUPERIOR_VENATOR);

	private SuperiorNpc()
	{
	}

	public static boolean isSuperior(int npcId)
	{
		return IDS.contains(npcId);
	}
}
